[workspace]
members = [
  "dioxus-web-component",
  "dioxus-web-component-macro",
  "examples/counter",
  "examples/greeting",
]
resolver = "2"

[workspace.package]
version = "0.0.4"
edition = "2021"
authors = ["ilaborie@gmail.com"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ilaborie/dioxus-web-component"
rust-version = "1.75.0"

[workspace.dependencies]
async-channel = "2.2.1"
dioxus = "0.5.1"
wasm-bindgen = "0.2.92"
web-sys = "0.3.68"
syn = "2.0.46"
quote = "1.0.35"
proc-macro2 = "1.0.74"
darling = "0.20.0"
heck = "0.5.0"

[workspace.lints.rust]
unsafe_code = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
perf = "warn"
pedantic = "warn"
cargo = "warn"

undocumented_unsafe_blocks = "deny"

dbg_macro = "warn"
expect_used = "warn"
if_then_some_else_none = "warn"
indexing_slicing = "warn"
large_include_file = "warn"
min_ident_chars = "warn"
print_stderr = "warn"
print_stdout = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
unnecessary_safety_doc = "warn"
unwrap_used = "warn"

module_name_repetitions = "allow"
