[package]
name = "dioxus-web-component"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

description = "Expose a Dioxus component as a Web Component"
categories = ["gui", "wasm", "web-programming"]
keywords = ["dioxus", "web-component", "wasm"]
readme = "README.md"

[features]
default = ["macros"]

macros = ["dep:dioxus-web-component-macro"]

[dependencies]
async-channel = { workspace = true }
dioxus = { workspace = true, default-features = true, features = ["web"] }
dioxus-web-component-macro = { version = "0.1.0", path = "../dioxus-web-component-macro", optional = true }
wasm-bindgen = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
  "CustomEvent",
  "ShadowRoot",
]

[lints]
workspace = true
